'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..'),tools=path.join(root,'tools'),results=path.join(root,'verification');
fs.mkdirSync(results,{recursive:true});process.env.TEMP=path.join(tools,'tmp');process.env.TMP=process.env.TEMP;
const {chromium}=require(path.join(tools,'playwright/package'));
const V=require('../vocabulary-core.js'),items=require('../vocabulary-data.js');
const url='http://127.0.0.1:4173/rail-english/',key='rail-english-v1',now=Date.parse('2026-10-05T11:00:00Z'),day='2026-10-05';
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:path.join(tools,'browser/chrome-win64/chrome.exe'),downloadsPath:results,env:{...process.env,TEMP:process.env.TEMP,TMP:process.env.TMP,USERPROFILE:path.join(tools,'browser-profile'),APPDATA:path.join(tools,'browser-profile/appdata'),LOCALAPPDATA:path.join(tools,'browser-profile/local')},args:['--no-first-run','--no-default-browser-check','--disable-crash-reporter']});
 const checks=[],errors=[];
 const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,acceptDownloads:true});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.clock.install({time:now});
 await page.goto(url);await page.waitForSelector('[data-action="vocab-start"]');
 await page.waitForFunction(()=>document.getElementById('offline-status').textContent.includes('準備完了'),{timeout:15000});
 const read=()=>page.evaluate(k=>JSON.parse(localStorage.getItem(k)),key);
 const confirm=async(confidence='clear')=>page.locator('[data-action="vocab-confirm"][data-confidence="'+confidence+'"]').click();
 const answer=async(wrong=false)=>{const id=await page.locator('[data-action="vocab-answer"]').first().getAttribute('data-item');const item=items.find(i=>i.id===id);await page.locator('[data-action="vocab-answer"][data-choice="'+(wrong?(item.answer+1)%4:item.answer)+'"]').click();return id;};
 assert.equal(await read(),null);checks.push('Opening app does not create or complete daily plan');
 await page.screenshot({path:path.join(results,'01-home-mobile.png'),fullPage:true});
 await page.locator('[data-action="vocab-start"]').click();
 const original=(await read()).vocabulary.days[day].ids;
 await answer(true);
 assert.equal(Object.keys((await read()).vocabulary.progress).length,0);
 await page.screenshot({path:path.join(results,'02-answer-mobile.png'),fullPage:true});
 await page.reload();await page.locator('[data-action="vocab-start"]').click();
 assert.equal(await page.locator('[data-action="vocab-answer"]:disabled').count(),4);
 const staleConfirm=await page.locator('[data-action="vocab-confirm"]').first().evaluate(el=>({...el.dataset}));
 await confirm('unsure');
 await page.evaluate(d=>{const b=document.createElement('button');Object.assign(b.dataset,d);document.body.append(b);b.click();b.click();b.remove();},staleConfirm);
 assert.equal((await read()).vocabulary.attempts.length,1);
 checks.push('Wrong pending answer survives reload; repeated stale confirmation cannot skip or credit the next item');
 await page.goBack();assert.ok(await page.locator('.vocabulary-hero').isVisible());
 await page.locator('[data-action="vocab-start"]').click();
 await answer();await confirm('unsure');checks.push('Browser Back preserves daily plan and progress');
 for(let i=2;i<5;i++){await answer();await confirm();}
 await page.waitForSelector('text=今日の学習、完了です。');
 const completed=await read();assert.ok(completed.vocabulary.days[day].completedAt);assert.equal(completed.vocabulary.attempts.length,5);assert.equal(completed.attempts.length,0);
 assert.equal(completed.vocabulary.progress[original[0]].stage,0);assert.equal(completed.vocabulary.progress[original[1]].stage,0);
 await page.screenshot({path:path.join(results,'03-complete-mobile.png'),fullPage:true});
 checks.push('5 distinct confidence-confirmed items complete day; wrong and unsure are not mastery; legacy attempts untouched');
 await page.locator('[data-route="settings"]').last().click();
 await page.locator('#vocab-new').selectOption('10');await page.locator('#vocab-reminder').check();
 assert.equal((await read()).vocabulary.settings.dailyNew,10);assert.deepEqual((await read()).vocabulary.days[day].ids,original);
 assert.ok((await page.locator('body').innerText()).includes('未接続・通知されません'));
 assert.equal(await page.evaluate(()=>Notification.permission),'default');
 await page.screenshot({path:path.join(results,'04-settings-mobile.png'),fullPage:true});
 checks.push('Quantity changes preserve today; reminder preference saves without notification permission request');
 const download=page.waitForEvent('download');await page.locator('[data-action="export"]').click();
 const backupPath=path.join(results,'roundtrip-backup.json');await(await download).saveAs(backupPath);
 const backup=JSON.parse(fs.readFileSync(backupPath,'utf8'));
 page.on('dialog',dialog=>dialog.accept());
 await page.locator('#vocab-new').selectOption('3');
 await page.locator('#backup-file').setInputFiles(backupPath);
 await page.waitForSelector('.vocabulary-hero');
 assert.deepEqual(await read(),backup.state);checks.push('Real export/import round-trip preserves complete state');
 await page.locator('[data-route="settings"]').last().click();
 await page.getByText('学習記録をリセットする',{exact:true}).click();
 await page.locator('[data-action="reset"]').click();
 const resetState=await read();
 assert.deepEqual(resetState.settings,backup.state.settings);
 assert.deepEqual(resetState.vocabulary.settings,backup.state.vocabulary.settings);
 assert.deepEqual(resetState.vocabulary.reminders,backup.state.vocabulary.reminders);
 assert.deepEqual(resetState.vocabulary.progress,{});assert.deepEqual(resetState.vocabulary.attempts,[]);
 checks.push('Explicit history reset keeps legacy settings, vocabulary quantity and reminder preference');
 await page.locator('#backup-file').setInputFiles(backupPath);await page.waitForSelector('.vocabulary-hero');
 await context.setOffline(true);await page.reload();
 await page.waitForSelector('.vocabulary-hero');await page.locator('[data-route="vocab-review"]').first().click();
 await page.locator('[data-action="vocab-practice"]').first().click();
 const practiceId=await answer();const dueBefore=(await read()).vocabulary.progress[practiceId].due;
 await confirm();assert.equal((await read()).vocabulary.progress[practiceId].due,dueBefore);
 await page.reload();assert.ok(await page.locator('.vocabulary-hero').isVisible());
 checks.push('Offline reload, examples, practice, save and reload work; early practice does not defer due');
 await context.setOffline(false);
 // Exercise real day-boundary UI with a pending answer and a held old button token.
 await page.clock.setSystemTime(Date.parse('2026-10-06T14:59:00Z'));
 await page.locator('[data-action="vocab-start"]').click();
 await answer();const old=await page.locator('[data-action="vocab-confirm"]').first().evaluate(el=>({...el.dataset}));
 await page.clock.setSystemTime(Date.parse('2026-10-06T15:00:00Z'));
 await page.evaluate(d=>{const b=document.createElement('button');Object.assign(b.dataset,d);document.body.append(b);b.click();b.remove();},old);
 assert.equal((await read()).vocabulary.days['2026-10-06'].completedAt,null);
 assert.equal((await read()).vocabulary.days['2026-10-07'],undefined);
 assert.ok((await page.locator('body').innerText()).includes('新しい日'));
 checks.push('JST midnight rejects stale confidence and cannot complete either day');
 // Narrow screens and large type on a live question.
 await page.locator('[data-action="vocab-start"]').click();
 for(const width of [320,375,390,768,1280]){
  await page.setViewportSize({width,height:844});
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
  assert.equal(overflow,false,'horizontal overflow at '+width);
 }
 await page.setViewportSize({width:320,height:800});await page.locator('[data-route="settings"]').last().click();await page.locator('#largeText').check();
 await page.locator('[data-route="home"]').last().click();await page.locator('[data-action="vocab-start"]').click();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.screenshot({path:path.join(results,'05-narrow-large-text.png'),fullPage:true});
 checks.push('No horizontal overflow at 320/375/390/768/1280px and 320px large text');
 // Restore a legacy backup, including a pending custom question.
 const raw=JSON.parse(fs.readFileSync(path.join(root,'app/index.html'),'utf8').match(/<script[^>]*id="question-data"[^>]*>([\s\S]*?)<\/script>/)[1]);
 const q={...raw.questions[0],id:'custom-ui-question',extension:{kept:true}};
 const legacy={schemaVersion:1,settings:{level:730,filter:'all',size:5,largeText:false,timer:true,futurePreference:9},progress:{[q.id]:{seen:1,correct:1,streak:0,due:now+86400000,needsReview:true,lastAt:now,futureProgress:true}},attempts:[{id:'legacy-a',qid:q.id,choice:q.answer,correct:true,type:'new',seconds:2,at:now,confidence:'pending',futureAttempt:'yes'}],session:{id:'legacy-s',mode:'daily',qids:[q.id],index:0,attemptIds:['legacy-a'],started:now,futureSession:4},lastResult:null,extraQuestions:[q],futureRoot:{kept:true}};
 await page.evaluate(({key,legacy})=>localStorage.setItem(key,JSON.stringify(legacy)),{key,legacy});await page.reload();
 await page.locator('[data-route="toeic"]').click();await page.locator('[data-action="resume"]').click();
 assert.equal(await page.locator('[data-action="answer"]:disabled').count(),4);
 await page.locator('[data-action="next"][data-confidence="clear"]').click();
 const after=await read();assert.equal(after.attempts.length,1);assert.equal(after.session,null);assert.equal(after.futureRoot.kept,true);assert.equal(after.attempts[0].futureAttempt,'yes');assert.equal(after.extraQuestions[0].extension.kept,true);assert.equal(Object.keys(after.vocabulary.progress).length,0);
 checks.push('Old custom-question pending session resumes in TOEIC mode; old fields and history preserved');
 // Malformed new state must not overwrite storage, and must expose recovery export.
 const invalid={...after,vocabulary:{schemaVersion:99}};const serialized=JSON.stringify(invalid);
 await page.evaluate(({key,serialized})=>localStorage.setItem(key,serialized),{key,serialized});await page.reload();
 assert.equal(await page.evaluate(k=>localStorage.getItem(k),key),serialized);
 await page.locator('[data-route="settings"]').last().click();assert.ok(await page.locator('[data-action="raw-export"]').isVisible());
 assert.equal(await page.evaluate(k=>localStorage.getItem(k),key),serialized);
 checks.push('Unrecognized vocabulary schema protects raw storage and offers recovery export');
 assert.deepEqual(errors,[]);
 const summary={browser:await browser.version(),checks,errors,passed:checks.length};
 fs.writeFileSync(path.join(results,'browser-results.json'),JSON.stringify(summary,null,2));console.log(JSON.stringify(summary,null,2));
 await browser.close();
})().catch(e=>{console.error(e);process.exitCode=1;});

