"""Original practice items. Not reproduced from official TOEIC materials."""
import json, random
from pathlib import Path
ROOT=Path(__file__).parent
items=[]

def cloze(level, skill, text, correct, wrong, translation, explanation):
    opts=[correct]+wrong.split('|')
    assert len(opts)==4, (text,opts)
    idx=len(items)+1
    random.Random(idx*173).shuffle(opts)
    items.append(dict(id=f'q{idx:03}',level=level,kind='cloze',skill=skill,text=text,options=opts,answer=opts.index(correct),translation=translation,explanation=explanation))

# Course 730: 30 foundational grammar and vocabulary questions.
cloze(730,'品詞','Please review the attached agenda _____ before tomorrow’s meeting.','carefully','careful|care|carefulness','明日の会議の前に、添付の議題を注意深く確認してください。','動詞 review（確認する）を修飾するので副詞 carefully。careful は形容詞、care と carefulness は名詞です。')
cloze(730,'日程・会議','The training session has been _____ until next Friday because the instructor is unavailable.','postponed','approved|attended|reserved','講師の都合がつかないため、研修は来週の金曜日まで延期されました。','postpone は「延期する」。has been postponed で受け身の現在完了形です。approve は承認する、attend は出席する、reserve は予約する。')
cloze(730,'前置詞','All expense reports must be submitted _____ 5 p.m. on Friday at the latest.','by','during|since|for','すべての経費報告書は、遅くとも金曜日の午後5時までに提出しなければなりません。','完了の期限「〜までに」には by。during は期間の中、since は起点、for は期間の長さを表します。')
cloze(730,'時制','Ms. Chen _____ in the sales department since 2021 and still works there.','has worked','will work|is working|had worked','チェンさんは2021年から営業部で働いており、今もそこで働いています。','since 2021 と今も続いているという情報から現在完了形 has worked。過去から現在までの継続を示します。')
cloze(730,'接続詞','_____ the weather was poor, the outdoor product demonstration went ahead as planned.','Although','Despite|Because of|During','天候は悪かったものの、屋外での製品実演は予定どおり行われました。','後ろに the weather was poor という主語＋動詞が続くので、逆接の接続詞 Although。Despite は名詞などを取ります。')
cloze(730,'品詞','The new reservation system is more _____ than the previous one.','reliable','reliably|reliability|rely','新しい予約システムは以前のものより信頼できます。','is の補語としてシステムの性質を述べる形容詞 reliable を選びます。more reliable than で比較の表現です。')
cloze(730,'語彙','Please keep your _____ as proof of payment.','receipt','recipe|reception|recipient','支払いの証明として領収書を保管してください。','receipt は領収書。recipe は調理法、reception は受付、recipient は受取人です。形の似た語を区別します。')
cloze(730,'主語と動詞','Each of the conference rooms _____ equipped with a projector.','is','are|have|were','会議室はそれぞれプロジェクターを備えています。','主語の中心は単数の Each。「each of ＋複数名詞」でも動詞は単数に合わせ、is equipped with とします。')
cloze(730,'動詞の形','Employees are encouraged _____ the online safety course.','to complete','complete|completed|completion','従業員はオンラインの安全講習を修了するよう奨励されています。','encourage 人 to do の受け身は、人 be encouraged to do。「〜するよう勧められる」です。')
cloze(730,'日程・会議','Could you _____ whether you will attend the meeting by replying to this message?','confirm','confuse|consume|compete','このメッセージに返信して、会議に出席するかどうかを確認していただけますか。','confirm whether ... は「〜かどうかを確認する」。confuse は混乱させる、consume は消費する、compete は競争する。')
cloze(730,'関係詞','The employee _____ organized the workshop will introduce the speakers.','who','which|whose|whom','研修会を企画した従業員が講演者を紹介します。','先行詞は人で、関係詞が organized の主語になるため who。whose は所有格、whom は目的格です。')
cloze(730,'前置詞','Visitors must check in at the reception desk _____ entering the laboratory.','before','until|since|between','訪問者は実験室に入る前に受付で手続きをしなければなりません。','before entering で「入る前に」。受付を済ませてから入室するという順序を表します。')
cloze(730,'比較','This route is _____ than the one we used yesterday.','shorter','shortest|shortly|shorten','この経路は昨日使ったものより短いです。','than があるので比較級 shorter。shortest は最上級、shortly は副詞、shorten は動詞です。')
cloze(730,'代名詞','The company updated _____ website to make online ordering easier.','its','it|itself|they','その会社はオンライン注文をしやすくするため、自社のウェブサイトを更新しました。','名詞 website の前で所有を示す its。「its＝それの」と「it’s＝it is」を区別しましょう。')
cloze(730,'語彙','The price includes delivery, so there is no _____ charge for shipping.','additional','available|annual|accurate','価格には配送料が含まれているので、配送の追加料金はありません。','additional charge は追加料金。available は利用できる、annual は年1回の、accurate は正確な。')
cloze(730,'動詞の形','We look forward to _____ you at the annual conference.','seeing','see|saw|seen','年次会議でお会いできることを楽しみにしています。','look forward to の to は前置詞なので、後ろは名詞か動名詞。ここでは seeing です。')
cloze(730,'接続詞','Please contact the help desk _____ you cannot access your account.','if','unless|despite|during','アカウントにアクセスできない場合は、ヘルプデスクに連絡してください。','条件「もし〜なら」を表す if。unless は「〜でない限り」で、ここでは意図が逆になります。')
cloze(730,'日程・会議','The manager asked us to _____ a meeting with the new supplier.','arrange','achieve|afford|apply','マネージャーは新しい仕入先との会議を手配するよう私たちに頼みました。','arrange a meeting は「会議を手配する」。achieve は達成する、afford は余裕がある、apply は応募・適用する。')
cloze(730,'受け身','The damaged items will _____ at no extra cost.','be replaced','replace|replacing|replacement','破損した商品は追加費用なしで交換されます。','商品は交換「される」側なので受け身。will の後は be ＋過去分詞で will be replaced。')
cloze(730,'品詞','Your _____ is required before we can process the order.','approval','approve|approved|approvingly','注文を処理するには、あなたの承認が必要です。','所有格 Your の後で主語になる名詞 approval を選びます。approve は動詞です。')
cloze(730,'語彙','The store offers a full _____ if an item is returned unused within 14 days.','refund','reward|revenue|reminder','商品が未使用のまま14日以内に返品されれば、その店は全額返金します。','full refund は全額返金。reward は報酬、revenue は売上高、reminder は注意を促す通知です。')
cloze(730,'数量','Only a _____ seats remain for the afternoon workshop.','few','little|much|every','午後の研修会の残席はわずかです。','seats は数えられる複数名詞なので a few。a little は数えられない名詞の量に使います。')
cloze(730,'時制','When the courier arrives tomorrow, the receptionist _____ the package.','will sign for','signed for|has signed for|had signed for','明日配達員が来たら、受付係が荷物の受領サインをします。','未来の出来事ですが、when の節では現在形 arrives。主節では未来を表す will sign for を使えます。')
cloze(730,'日程・会議','Please let me know which of the proposed dates is most _____ for you.','convenient','conveniently|convenience|convene','提案した日程のうち、どれが最も都合がよいか教えてください。','is の後に性質を表す形容詞 convenient。「都合のよい」という意味で、日程調整によく合う表現です。')
cloze(730,'前置詞','Mr. Patel is responsible _____ maintaining the customer database.','for','to|at|with','パテルさんは顧客データベースの管理を担当しています。','be responsible for ＋名詞・動名詞で「〜を担当している／〜に責任がある」です。')
cloze(730,'接続詞','The elevator is out of service, _____ please use the stairs.','so','or|although|unless','エレベーターは運転を停止しているので、階段を利用してください。','前半が理由で後半が結果・依頼なので so。「そのため」というつながりを作ります。')
cloze(730,'語彙','A _____ of the updated brochure is attached to this email.','copy','fare|venue|shift','更新したパンフレットの写しをこのメールに添付しています。','a copy of は「〜の写し／1部」。fare は運賃、venue は会場、shift は勤務時間帯です。')
cloze(730,'品詞','The technician _____ identified the cause of the problem.','quickly','quick|quicker|quickness','技術者は問題の原因を素早く特定しました。','動詞 identified を修飾する副詞 quickly を選びます。形容詞 quick と名詞 quickness はこの位置に入りません。')
cloze(730,'動詞の形','The company plans _____ a second office next year.','to open','opening|opened|opens','その会社は来年、2つ目の事務所を開設する予定です。','plan to do で「〜する予定だ」。plans の目的を表す to open を選びます。')
cloze(730,'日程・会議','The meeting will _____ at 9 a.m. sharp, so please arrive a few minutes early.','begin','beginning|began|begun','会議は午前9時ちょうどに始まるので、数分早めに到着してください。','助動詞 will の後は動詞の原形 begin。at 9 a.m. sharp は「午前9時ちょうどに」です。')

# Course 800: 30 intermediate contextual and grammatical questions.
cloze(800,'接続詞','The client approved the design, _____ that the final version includes a larger logo.','provided','despite|during|whereas','顧客は最終版により大きなロゴを入れることを条件に、そのデザインを承認しました。','provided that ... は「〜という条件で」。ここでは承認の条件を述べています。whereas は対比です。')
cloze(800,'数量','_____ of the two proposals meets all of our requirements, so we need a third option.','Neither','Both|Every|All','2つの提案はどちらも当社の要件をすべて満たさないので、3つ目の選択肢が必要です。','neither of the two は「2つのうちどちらも〜ない」。単数動詞 meets と結びつき、文末の事情とも一致します。')
cloze(800,'動詞の形','The supervisor had the technician _____ the faulty sensor.','replace','to replace|replaced|replacement','監督者は技術者に故障したセンサーを交換してもらいました。','have ＋人＋動詞の原形は「人に〜してもらう／させる」。have ＋物＋過去分詞との違いに注意します。')
cloze(800,'前置詞','_____ the increase in material costs, the company has kept its prices unchanged.','Despite','Although|Even|Whereas','材料費の上昇にもかかわらず、その会社は価格を据え置いています。','空欄の後は名詞句 the increase ... なので前置詞 Despite。Although と Whereas の後には原則として節が必要です。')
cloze(800,'時制','By the time the auditors arrived, the finance team _____ all the requested documents.','had prepared','prepares|will prepare|has prepared','監査担当者が到着するまでに、経理チームは要求されたすべての書類を準備し終えていました。','過去の到着より前に準備が完了したため、過去完了形 had prepared を使います。')
cloze(800,'語彙','The warranty does not _____ damage caused by improper use.','cover','collect|consume|conduct','保証は不適切な使用による損傷を対象としていません。','cover は保証・保険などが「〜を対象とする」。collect は集める、consume は消費する、conduct は実施する。')
cloze(800,'関係詞','The consultant, _____ recommendations reduced our costs, will return next month.','whose','who|whom|which','その助言によって当社の費用が削減されたコンサルタントが、来月再び来訪します。','recommendations の所有者を示す whose。「その人の助言」という関係です。')
cloze(800,'動詞の形','The revised schedule allows enough time for the equipment _____ before the event.','to be tested','testing|has tested|was testing','改訂された日程には、イベントの前に機材を試験するための十分な時間があります。','for ＋対象＋to do の形。equipment は試験される側なので受け身の不定詞 to be tested を使います。')
cloze(800,'日程・会議','Please _____ the updated schedule to everyone who will attend the workshop.','circulate','commute|compare|compete','研修会に出席する全員に、更新した日程を回覧してください。','circulate は資料などを「回覧する／配布する」。commute は通勤する、compare は比較する、compete は競争する。')
cloze(800,'比較','The revised manual explains the installation process _____ more clearly than the original.','far','very|many|quite','改訂版のマニュアルは、初版よりもはるかに明確に設置手順を説明しています。','比較級 more clearly を強めるのは far。very は通常、この形の比較級を直接修飾しません。')
cloze(800,'接続詞','Applicants must provide two references _____ they have previous experience with our company.','even if','so that|as soon as|now that','以前に当社で働いた経験があっても、応募者は照会先を2件提出しなければなりません。','even if は「たとえ〜でも」。経験の有無にかかわらず必要という条件を示します。')
cloze(800,'語彙','After reviewing the figures, we decided to _____ our sales forecast downward.','revise','retain|resolve|recruit','数値を確認した後、私たちは売上予測を下方修正することにしました。','revise a forecast は予測を修正する。retain は保持する、resolve は解決する、recruit は採用する。')
cloze(800,'品詞','The proposed changes would _____ improve access for customers with limited mobility.','significantly','significant|significance|signify','提案された変更は、移動に制約のある顧客の利用しやすさを大幅に改善するでしょう。','動詞 improve を修飾する副詞 significantly。「大幅に／著しく」という意味です。')
cloze(800,'動詞の形','The manager recommended that the report _____ before it was sent to the client.','be revised','is revising|to revise|revises','マネージャーは、顧客に送る前に報告書を修正するよう勧めました。','提案を表す recommend that の節では動詞の原形を使う形があります。report は修正される側なので be revised。')
cloze(800,'前置詞','All contractors must comply _____ the building’s safety regulations.','with','at|for|from','すべての請負業者は、その建物の安全規則に従わなければなりません。','comply with は「規則などに従う」。前置詞も含めたまとまりで覚えます。')
cloze(800,'時制','This time next week, our team _____ the new system at the trade fair.','will be demonstrating','had demonstrated|demonstrates|has demonstrated','来週の今ごろ、私たちのチームは展示会で新システムを実演しているでしょう。','未来のある時点で進行中の動作なので未来進行形 will be demonstrating が適切です。')
cloze(800,'語彙','The hotel can _____ up to 300 guests in its main dining room.','accommodate','accumulate|accomplish|accompany','そのホテルのメインダイニングは最大300人の客を収容できます。','accommodate は「収容する」。accumulate は蓄積する、accomplish は達成する、accompany は同行する。')
cloze(800,'接続詞','The shipment will be delayed _____ the missing customs documents are received.','until','during|in spite of|because of','不足している通関書類を受領するまで、出荷は遅れます。','until ＋節で「〜するまで」。後ろには主語と動詞があるため、名詞を取る during などは使えません。')
cloze(800,'代名詞','The two designs are similar, but the newer _____ uses less material.','one','ones|another|other','2つのデザインは似ていますが、新しい方は材料をあまり使いません。','単数の design を繰り返さずに示す one。the newer one で「より新しい方」です。')
cloze(800,'語彙','The contract is _____ for one year from the date of signing.','valid','vacant|versatile|visible','その契約は署名日から1年間有効です。','valid は契約などが有効な。vacant は空いている、versatile は多用途の、visible は見える。')
cloze(800,'動詞の形','_____ the revised figures, the analyst updated her presentation.','Having reviewed','Have reviewed|To reviewing|Has reviewed','修正された数値を確認してから、分析担当者はプレゼンテーションを更新しました。','Having ＋過去分詞の分詞構文は、主節の動作より前に完了した動作を示せます。数値を確認した後で更新しました。')
cloze(800,'関係詞','The office _____ the interviews will take place is on the third floor.','where','which|what|who','面接が行われる事務所は3階にあります。','後ろの the interviews will take place は場所を補えばよい節。where は in which に相当します。')
cloze(800,'日程・会議','We need to _____ the schedule change with the catering team before notifying participants.','coordinate','calculate|conclude|compensate','参加者に知らせる前に、ケータリング担当チームと日程変更を調整する必要があります。','coordinate ... with ... は「〜を…と調整する」。calculate は計算する、conclude は結論づける、compensate は補償する。')
cloze(800,'数量','There is _____ information in the brochure to help you choose the appropriate course.','enough','many|a few|several','パンフレットには適切なコースを選ぶのに十分な情報があります。','information は数えられない名詞。enough information は可能ですが、many、a few、several は可算名詞の複数形に使います。')
cloze(800,'語彙','The director asked for a _____ summary rather than a detailed explanation.','concise','costly|complex|confidential','責任者は詳しい説明ではなく、簡潔な要約を求めました。','rather than a detailed explanation という対比から concise（簡潔な）。confidential は機密のという別の性質です。')
cloze(800,'主語と動詞','The list of approved suppliers _____ updated every quarter.','is','are|have|were','承認された仕入先の一覧は四半期ごとに更新されます。','主語の中心は単数の list。近くの複数名詞 suppliers ではなく list に合わせて is updated とします。')
cloze(800,'受け身','Customers are advised _____ their passwords regularly.','to change','changing|changed|change','顧客はパスワードを定期的に変更するよう勧められています。','advise 人 to do の受け身は be advised to do。助言される人が主語です。')
cloze(800,'接続詞','The team added a second registration desk _____ attendees would not have to wait as long.','so that','even though|in case of|rather than','参加者の待ち時間が短くなるよう、チームは受付窓口をもう1つ設けました。','so that ＋節で「〜するために」という目的を表します。even though は逆接です。')
cloze(800,'語彙','The manufacturer has _____ production to meet the unexpected rise in demand.','increased','interrupted|inspected|inherited','メーカーは予想外の需要増に対応するため、生産を増やしました。','需要増に対応するので increased production。interrupt は中断する、inspect は検査する、inherit は受け継ぐ。')
cloze(800,'比較','Of the three locations under consideration, this one is the _____ accessible by public transport.','most','more|much|many','検討中の3つの場所のうち、ここが公共交通機関で最も行きやすい場所です。','3つの中で最もという最上級なので the most accessible。more は比較級です。')

# Course 850: 30 advanced practice questions. These levels are editorial, not score predictions.
cloze(850,'倒置','Only after the inspection _____ permission to reopen the facility.','did the manager receive','the manager received|the manager had received|received the manager','検査が終わって初めて、マネージャーは施設を再開する許可を受けました。','Only after ... が文頭に来ると、主節で倒置が起きます。過去の一般動詞なので did ＋主語＋原形 receive。')
cloze(850,'語彙','The preliminary agreement is not legally _____ until both parties sign the final contract.','binding','bound|bind|binds','予備的な合意は、両当事者が最終契約に署名するまでは法的拘束力を持ちません。','legally binding は「法的拘束力のある」。binding が agreement の性質を表す形容詞として働きます。')
cloze(850,'接続詞','The project can proceed _____ the final budget is approved by the board.','provided that','regardless of|in addition to|as opposed to','最終予算が取締役会に承認されることを条件に、その計画は進められます。','後ろは節なので provided that（〜という条件で）。他の選択肢はいずれも、この形で主語＋動詞の節を直接取れません。')
cloze(850,'語彙','The two departments must work together to _____ the transition to the new software.','facilitate','fluctuate|forfeit|forecast','新ソフトウェアへの移行を円滑に進めるため、2つの部署は協力しなければなりません。','facilitate は「容易にする／円滑にする」。fluctuate は変動する、forfeit は失う、forecast は予測する。')
cloze(850,'時制','By the end of next month, the engineers _____ the bridge repairs.','will have completed','had completed|have completed|were completing','来月末までに、技術者たちは橋の補修を終えているでしょう。','未来の期限までの完了を示す未来完了形 will have completed。by the end of next month が手がかりです。')
cloze(850,'動詞の形','The proposal is worth _____ despite the initial cost.','considering','to consider|consider|considered','初期費用はかかるものの、その提案には検討する価値があります。','be worth doing で「〜する価値がある」。to 不定詞ではなく動名詞 considering を使います。')
cloze(850,'語彙','The figures in the two reports do not match; please investigate the _____.','discrepancy','consistency|compliance|consensus','2つの報告書の数値が一致しません。その食い違いを調べてください。','discrepancy は「不一致／食い違い」。consistency は一貫性、compliance は順守、consensus は合意です。')
cloze(850,'倒置','Had we received the notice earlier, we _____ alternative arrangements.','would have made','will make|had made|would making','もっと早く通知を受けていれば、代わりの手配をしていたでしょう。','Had we received ... は If we had received ... の if を省略した倒置。過去の反実仮想なので would have made。')
cloze(850,'前置詞','Payment is due within 30 days _____ receipt of the invoice.','of','between|along|toward','支払い期限は請求書の受領から30日以内です。','within 30 days of ... は「〜から30日以内」。基準となる出来事を of の後に置きます。')
cloze(850,'語彙','The expansion plan remains _____ on securing additional funding.','contingent','competent|consecutive|comparable','拡張計画の実施は、依然として追加資金の確保を条件としています。','be contingent on は「〜次第である／〜を条件とする」。competent は有能な、consecutive は連続した、comparable は比較可能な。')
cloze(850,'関係詞','The committee received six applications, two of _____ were submitted after the deadline.','which','them|whose|what','委員会は6件の応募を受け取り、そのうち2件は締め切り後に提出されました。','カンマの後を関係詞でつなぐ two of which。「そのうち2件」を表します。two of them だけでは文をこの形で接続できません。')
cloze(850,'動詞の形','With all the necessary permits _____, construction can begin next week.','obtained','obtain|obtaining|to obtaining','必要な許可がすべて取得されたので、来週建設を開始できます。','with ＋名詞＋補語の形。permits は取得される側なので過去分詞 obtained を使います。')
cloze(850,'語彙','The new procedure will _____ the need for staff to enter the same data twice.','eliminate','elaborate|estimate|encounter','新しい手順によって、職員が同じデータを2度入力する必要がなくなります。','eliminate the need for ... は「〜の必要をなくす」。elaborate は詳しく説明する、estimate は見積もる、encounter は遭遇する。')
cloze(850,'接続詞','_____ demand continue to rise, the company will open a second production line.','Should','Unless|Whether|Despite','需要が引き続き増加する場合、その会社は2本目の生産ラインを稼働させます。','Should ＋主語＋動詞の原形は、if を使わずに「もし〜なら」を表す条件の倒置です。')
cloze(850,'比較','The more clearly the requirements are defined, the _____ misunderstandings there will be.','fewer','less|least|fewest','要件を明確に定めれば定めるほど、誤解は少なくなります。','the ＋比較級 ..., the ＋比較級 ... の構文。misunderstandings は複数の可算名詞なので fewer。')
cloze(850,'語彙','Because of the venue’s limited capacity, attendance is _____ to registered delegates.','restricted','restored|referred|recruited','会場の収容人数が限られているため、参加は登録済みの代表者に制限されています。','be restricted to は「〜に限定される」。restore は復旧する、refer は言及する、recruit は募集する。')
cloze(850,'品詞','The replacement parts are _____ available from authorized dealers.','readily','ready|readiness|readied','交換部品は正規販売店で容易に入手できます。','readily available は「容易に入手できる」。副詞 readily が形容詞 available を修飾します。')
cloze(850,'動詞の形','The supplier denied _____ the specifications without prior approval.','changing','to change|change|changes','仕入先は、事前承認なしに仕様を変更したことを否定しました。','deny は目的語に動名詞を取る動詞です。deny doing で「〜したことを否定する」。')
cloze(850,'語彙','The director’s main _____ is that the proposed timetable leaves no room for testing.','concern','consent|consequence|contribution','責任者の主な懸念は、提案された日程には試験の余地がないことです。','concern は懸念。consent は同意、consequence は結果、contribution は貢献です。that 節が懸念の内容を説明します。')
cloze(850,'接続詞','No matter _____ carefully the budget is prepared, unexpected expenses may arise.','how','what|which|whose','予算をどれほど入念に作成しても、予想外の支出が生じる可能性があります。','no matter how ＋形容詞・副詞で「どれほど〜でも」。ここでは副詞 carefully の程度を表します。')
cloze(850,'語彙','The revised policy will _____ all previous versions when it takes effect on October 1.','supersede','subscribe|subsidize|supervise','改訂された方針は10月1日に発効すると、以前のすべての版に取って代わります。','supersede は「取って代わる」。subscribe は購読する、subsidize は補助金を出す、supervise は監督する。')
cloze(850,'動詞の形','We would appreciate _____ informed of any changes to the delivery date.','being kept','to keep|keeping us|keep','納品日の変更があれば、お知らせいただけると幸いです。','appreciate は動名詞を取ります。私たちは情報を知らされる側なので being kept informed（知らされていること）。')
cloze(850,'語彙','The trial results were _____, so further testing is needed before a decision can be made.','inconclusive','inevitable|inflexible|inexpensive','試験結果では結論が出なかったため、決定する前に追加の試験が必要です。','inconclusive は結論を導けない。inevitable は避けられない、inflexible は柔軟性がない、inexpensive は安価な。')
cloze(850,'関係詞','_____ is selected for the role will receive training before starting work.','Whoever','Whomever|Whose|Whom','その職務に誰が選ばれても、勤務開始前に研修を受けます。','Whoever が is selected の主語になり、節全体が will receive の主語になります。Whomever は目的格です。')
cloze(850,'語彙','The company agreed to _____ employees for travel expenses incurred during the project.','reimburse','remind|resume|relocate','その会社は、プロジェクト中に発生した旅費を従業員に払い戻すことに同意しました。','reimburse 人 for 費用 で「人に費用を払い戻す」。remind は思い出させる、resume は再開する、relocate は移転させる。')
cloze(850,'動詞の形','The equipment must be inspected before _____ put back into service.','being','be|been|is','その機器は再び使用する前に点検しなければなりません。','before の後で受け身を作る動名詞 being put。before it is put ... の it を省いて is だけにはできません。')
cloze(850,'語彙','Demand is expected to _____ during the winter, then recover in spring.','decline','delegate|derive|depict','需要は冬の間に減少し、春に回復すると予想されています。','recover と対になる decline（減少する）。delegate は委任する、derive は由来する、depict は描写する。')
cloze(850,'数量','_____ information has been provided about the proposed merger, leaving investors uncertain.','Little','Few|Many|Several','提案された合併についてはほとんど情報が提供されておらず、投資家は見通しを持てずにいます。','information は不可算名詞なので Little。「ほとんど〜ない」という否定的な意味が leaving investors uncertain と一致します。')
cloze(850,'語彙','The firm is seeking a _____ solution that can be maintained without exceeding its budget.','sustainable','susceptible|successive|superficial','その会社は、予算を超えずに維持できる持続可能な解決策を求めています。','sustainable は持続可能な。susceptible は影響を受けやすい、successive は連続する、superficial は表面的な。')
cloze(850,'接続詞','The offer applies to all items in stock, _____ those already marked down.','except','unless|although|whereas','その特典は、すでに値下げされたものを除く、在庫のあるすべての商品に適用されます。','except ＋名詞句で「〜を除いて」。those already marked down は「すでに値下げされた商品」です。')

# Reading: 15 original documents/sets, two questions each.
def reading(level, name, passage, rows):
    for text,correct,wrong,translation,explanation,proof in rows:
        idx=len(items)+1; opts=[correct]+wrong.split('|')
        assert len(opts)==4
        random.Random(idx*173).shuffle(opts)
        items.append(dict(id=f'q{idx:03}',level=level,kind='reading',skill='読解',title=name,passage=passage,text=text,options=opts,answer=opts.index(correct),translation=translation,explanation=explanation,proof=proof))

reading(730,'日程変更のメール', 'To: Sales Team\nSubject: Thursday’s meeting\n\nThursday’s sales meeting has been moved from Room 2 to Room 5 because a projector is being repaired in Room 2. The starting time remains 10:00 a.m. Please bring a printed copy of your monthly results.', [
('What has changed about the meeting?','Its location','Its date|Its starting time|Its topic','質問：会議について何が変更されましたか。\n正解：場所。','Room 2 から Room 5 への変更です。開始時刻は remains（変わらない）と明記されています。','has been moved from Room 2 to Room 5'),
('What should team members bring?','A paper copy of their results','A new projector|A list of customers|A room reservation form','質問：チームのメンバーは何を持参する必要がありますか。\n正解：業績の紙の写し。','printed copy が paper copy に言い換えられています。','Please bring a printed copy of your monthly results.')])
reading(730,'配達のお知らせ','Delivery update\n\nYour desk was scheduled to arrive on Tuesday. Due to a vehicle problem, it will now arrive on Wednesday between 1:00 and 3:00 p.m. If this time is inconvenient, call us by 6:00 p.m. today to arrange another delivery time. There is no additional charge.',[
('When will the desk now arrive?','On Wednesday afternoon','On Tuesday morning|On Tuesday afternoon|On Wednesday morning','質問：机は変更後、いつ到着しますか。\n正解：水曜日の午後。','変更前の Tuesday ではなく、it will now arrive の後の Wednesday と午後1〜3時を確認します。','it will now arrive on Wednesday between 1:00 and 3:00 p.m.'),
('Why would a customer call the company?','To request a different delivery time','To pay an extra fee|To order a replacement desk|To report a missing instruction sheet','質問：顧客は何のために会社へ電話しますか。\n正解：別の配達時間を依頼するため。','都合が悪い場合に別の時間を調整するための電話です。追加料金は不要です。','call us by 6:00 p.m. today to arrange another delivery time')])
reading(730,'研修会の案内','New employee workshop\n\nThe customer service workshop will take place on June 12 from 2:00 to 4:00 p.m. in the training center. All new employees must attend. Experienced employees may join if space is available. Register through the staff website by June 5.',[
('Who is required to attend?','All new employees','Only department managers|All experienced employees|Customers with complaints','質問：出席が義務づけられているのは誰ですか。\n正解：新入社員全員。','must attend は出席義務、may join は参加可能という意味です。対象を混同しないようにします。','All new employees must attend.'),
('How should employees register?','Through the staff website','By calling the training center|By visiting customer service|By replying to a printed notice','質問：従業員はどのように登録しますか。\n正解：職員向けウェブサイトから。','Register through ... の後に登録方法が示されています。','Register through the staff website by June 5.')])
reading(730,'店舗営業時間の案内','Harbor Office Supplies\n\nStarting April 1, our store will open at 8:00 a.m. on weekdays, one hour earlier than before. Saturday hours will remain 10:00 a.m. to 6:00 p.m. We are closed on Sundays. Online orders can be placed at any time.',[
('What time did the store previously open on weekdays?','At 9:00 a.m.','At 7:00 a.m.|At 8:00 a.m.|At 10:00 a.m.','質問：以前の平日の開店時刻は何時でしたか。\n正解：午前9時。','新しい開店時刻は8時で、以前より1時間早いので、以前は9時です。','8:00 a.m. on weekdays, one hour earlier than before'),
('What is available on Sundays?','Placing an order online','Shopping inside the store|Collecting an order at the store|Attending a sales event','質問：日曜日に利用できるのは何ですか。\n正解：オンラインで注文すること。','店舗は日曜休業ですが、オンライン注文は at any time（いつでも）可能です。','Online orders can be placed at any time.')])
reading(730,'備品貸出のメモ','To all staff\n\nPortable projectors can be borrowed from the IT desk for up to three days. Please reserve one at least two working days before you need it. Return all cables with the projector. Staff who need equipment for longer should contact the IT manager before making a reservation.',[
('How far in advance should a projector be reserved?','At least two working days','At least three calendar days|One week|On the day it is needed','質問：プロジェクターは少なくともどれだけ前に予約すべきですか。\n正解：2営業日前。','貸出期間の3日と、予約期限の2営業日前を区別します。','at least two working days before you need it'),
('What should staff do to borrow equipment for more than three days?','Contact the IT manager first','Return the cables separately|Make two online reservations|Ask a colleague to collect it','質問：3日を超えて機材を借りるには何をすべきですか。\n正解：最初にITマネージャーへ連絡する。','長期利用は予約前に相談が必要です。','contact the IT manager before making a reservation')])

reading(800,'ホテルからの返信','Dear Ms. Rivera,\n\nWe can accommodate your group of 18 in our private dining room on August 22. The room is available from 6:30 p.m., but your requested 6:00 p.m. start is not possible because of an earlier event. The meal price includes coffee and tea; other soft drinks are charged separately. Please confirm the revised time by Friday to secure the room.\n\nBest regards,\nHarbor Hotel',[
('What does the hotel ask Ms. Rivera to confirm?','Whether a later starting time is acceptable','Whether the group has fewer than 18 people|Whether the event can move to another date|Whether coffee should be removed from the menu','質問：ホテルはリベラさんに何の確認を求めていますか。\n正解：開始時刻を遅らせてもよいか。','希望の6時ではなく6時半からなら可能です。revised time はこの変更を指します。','Please confirm the revised time by Friday to secure the room.'),
('Which statement is supported by the email?','Some nonalcoholic drinks cost extra','All beverages are included in the meal price|The dining room holds no more than 18 people|The room is available throughout the evening','質問：メールに合致するのはどれですか。\n正解：一部のノンアルコール飲料は追加料金がかかる。','コーヒーと紅茶は料金に含まれますが、other soft drinks は別料金です。18人を収容できることから最大定員までは断定できません。','other soft drinks are charged separately')])
reading(800,'在庫変更と注文','Subject: Order 481\n\nThe blue notebooks you ordered are temporarily unavailable. We can ship the same model in gray immediately, or send the blue ones when they arrive in approximately two weeks. Both colors are the same price. Unless we hear from you by noon tomorrow, we will keep your order unchanged and wait for the blue notebooks.',[
('What will happen if the customer does not reply?','The company will wait to ship the blue notebooks','The order will be canceled|Gray notebooks will be shipped immediately|The customer will receive both colors','質問：顧客が返信しない場合、どうなりますか。\n正解：会社は青いノートの発送を待つ。','Unless we hear from you（連絡がない限り）に続く既定の対応を読み取ります。','we will keep your order unchanged and wait for the blue notebooks'),
('What is an advantage of choosing gray notebooks?','They can be dispatched sooner','They have a lower price|They are a larger model|They include free accessories','質問：灰色のノートを選ぶ利点は何ですか。\n正解：より早く発送できる。','ship immediately が dispatched sooner に言い換えられています。価格は同じです。','We can ship the same model in gray immediately')])
reading(800,'展示会のチャット','Mina, 9:10: The sample boxes arrived, but the printed brochures are still missing.\nAlex, 9:12: The courier expects to deliver them at 11. Our booth opens at 10.\nMina, 9:14: Then let’s display the QR code for the digital brochure until they get here.\nAlex, 9:15: Good idea. I’ll print a large sign now.',[
('What problem are Mina and Alex addressing?','Visitors will arrive before the printed brochures do','The sample boxes contain the wrong products|The digital brochure cannot be opened|The booth has been assigned the wrong location','質問：ミナとアレックスは何の問題に対応していますか。\n正解：印刷パンフレットが届く前に来場者が来ること。','ブースの開始は10時、パンフレットの到着予定は11時。この時間差が問題です。','The courier expects to deliver them at 11. Our booth opens at 10.'),
('What will Alex most likely put on the sign?','A QR code for a brochure','A notice canceling the event|A new delivery address|A list of courier charges','質問：アレックスは案内表示におそらく何を載せますか。\n正解：パンフレット用のQRコード。','QRコードを掲示する提案に Good idea と応じ、sign を印刷すると言っています。','let’s display the QR code for the digital brochure')])
reading(800,'社内制度の更新','Remote work update\n\nFrom September, employees may work remotely up to two days per week after receiving their supervisor’s approval. The policy does not apply during the first three months of employment. Teams must still arrange at least one day each week when all members work in the office. Existing equipment allowances will not change.',[
('Who cannot yet use the new policy?','An employee who joined one month ago','An employee who works in a large team|A supervisor with five years of service|An employee who already owns a laptop','質問：まだ新制度を利用できないのは誰ですか。\n正解：1か月前に入社した従業員。','入社後3か月間は対象外なので、入社1か月の人は利用できません。','The policy does not apply during the first three months of employment.'),
('What must each team do?','Choose a weekly day for everyone to attend the office','Increase its equipment allowance|Work remotely on the same two days|Request permission from every department','質問：各チームは何をしなければなりませんか。\n正解：全員が出社する曜日を毎週設ける。','週に少なくとも1日は全員が出社するよう調整するという要件です。','at least one day each week when all members work in the office')])
reading(800,'修理サービスの案内','Dear Mr. Owens,\n\nWe have inspected your printer. The damaged roller is covered by your service plan, so there is no repair charge. However, the replacement part must be ordered and will arrive on Monday. Repair should be completed the following day. A loan printer is available at no cost if you collect it from our service center.',[
('When is the repair expected to be finished?','On Tuesday','On Sunday|On Monday|On Wednesday','質問：修理はいつ完了する見込みですか。\n正解：火曜日。','部品到着が月曜日、その翌日に完了するので火曜日です。','will arrive on Monday. Repair should be completed the following day.'),
('What is required to use the loan printer for free?','Picking it up at the service center','Paying for the replacement roller|Extending the service plan|Returning the original printer first','質問：代替プリンターを無料で利用するには何が必要ですか。\n正解：サービスセンターで受け取ること。','if you collect it が無料貸出の条件です。修理代が無料であることとは別の条件です。','at no cost if you collect it from our service center')])

reading(850,'案内と返信の照合','DOCUMENT 1 — Seminar notice\n\nThe professional writing seminar on May 18 costs $120 per person. Groups of five or more receive a 15% discount if a single payment is made for the whole group. Registration closes May 10. A digital workbook is included.\n\nDOCUMENT 2 — Email\n\nHi Nora,\nFour colleagues and I will attend the May 18 seminar. Please register all of us together and make one payment using the department card. We do not need printed workbooks. Thanks, Leo.',[
('How much should Nora pay for the group?','$510','$408|$480|$600','質問：ノラはグループ分としていくら支払うべきですか。\n正解：510ドル。','Four colleagues and I は5人。5人で一括払いなので15%引きです。120×5×0.85＝510。','Groups of five or more receive a 15% discount if a single payment is made'),
('Why does Leo ask Nora to make one payment?','To meet a condition for the group discount','To receive a free printed workbook|To register after the deadline|To reserve a private classroom','質問：レオが一括払いを頼むのはなぜですか。\n正解：団体割引の条件を満たすため。','案内の条件と、メールの make one payment を照合します。印刷物に関する割引は記載されていません。','if a single payment is made for the whole group')])
reading(850,'会場一覧と依頼の照合','DOCUMENT 1 — Available rooms, October 6\n\nOak: up to 24 people; available 9 a.m.–noon; projector included.\nMaple: up to 40 people; available 1–5 p.m.; projector included.\nPine: up to 32 people; available 9 a.m.–5 p.m.; no projector.\n\nDOCUMENT 2 — Email\n\nWe need a room for 30 people from 2 to 4 p.m. on October 6. A projector is essential, and we cannot bring our own. Please book a room that meets all three requirements.',[
('Which room meets all the requirements?','Maple','Oak|Pine|None of the rooms','質問：すべての条件に合う部屋はどれですか。\n正解：Maple。','30人・午後2〜4時・プロジェクターの3条件を照合します。Oak は定員と時間、Pine は機材が合いません。','Maple: up to 40 people; available 1–5 p.m.; projector included.'),
('Why is Pine unsuitable?','It lacks a required piece of equipment','It is too small for the group|It is unavailable in the afternoon|It can only be rented for a full day','質問：Pine が不適切なのはなぜですか。\n正解：必要な機材がないため。','定員と時間は満たしますが、projector is essential に対して no projector です。','Pine: up to 32 people; available 9 a.m.–5 p.m.; no projector.')])
reading(850,'採用担当者のメール','Dear Ms. Ahmed,\n\nYour experience closely matches our needs, and we would like to invite you to a final interview. We had hoped to meet in person; however, the hiring manager will be traveling throughout the interview week. A video interview would therefore be the most practical option. Please send two suitable time slots, taking into account that our office is three hours behind your local time.\n\nRegards,\nRecruitment Team',[
('Why does the recruitment team propose a video interview?','The hiring manager will be away','The applicant lacks relevant experience|The office has permanently closed|The company no longer holds final interviews','質問：採用担当者がビデオ面接を提案するのはなぜですか。\n正解：採用マネージャーが不在になるため。','当初は対面を希望したが、マネージャーが出張中なのでビデオが現実的だという流れです。','the hiring manager will be traveling throughout the interview week'),
('If Ms. Ahmed proposes 3 p.m. in her local time, what time is it at the office?','12 noon','9 a.m.|3 p.m.|6 p.m.','質問：アーメドさんが現地時間の午後3時を提案した場合、事務所では何時ですか。\n正解：正午。','事務所は本人の現地時間より3時間遅いので、15時−3時間＝12時です。','our office is three hours behind your local time')])
reading(850,'提案への慎重な返信','Dear Daniel,\n\nThe pilot program has reduced processing time, which is encouraging. Still, the test involved only our smallest branch. Before committing to a company-wide launch, I would like to see results from a location with a much higher transaction volume. Could you extend the trial to the Central branch and report back at the end of the month?\n\nHelen',[
('What is Helen’s position on a company-wide launch?','She wants broader evidence before deciding','She has approved it without conditions|She believes the pilot has failed entirely|She wants to abandon the software immediately','質問：全社導入に対するヘレンの立場はどれですか。\n正解：決定前に、より広い条件での根拠を求めている。','効果は認めていますが、小規模支店だけでは判断せず、大量の取引がある支店の結果を求めています。','Before committing to a company-wide launch, I would like to see results from a location with a much higher transaction volume.'),
('Why is the Central branch most likely being selected?','It can test the program under a heavier workload','It has already finished the trial|It is the company’s smallest location|It has requested shorter opening hours','質問：Central 支店が選ばれた理由として最も考えられるのはどれですか。\n正解：より大きい業務量でプログラムを試せるため。','高い取引量の場所の結果がほしいと述べ、その直後に Central 支店への拡張を依頼しています。文脈からの推論です。','a location with a much higher transaction volume')])
reading(850,'変更通知と顧客の返信','DOCUMENT 1 — Supplier notice\n\nEffective July 1, orders below $200 will incur a $15 shipping fee. Orders of $200 or more will continue to ship free. The threshold is based on the value of goods after discounts, excluding tax.\n\nDOCUMENT 2 — Customer email, July 3\n\nOur order total is $210 before our 10% loyalty discount and before tax. I assumed delivery would be free, but a shipping fee appears at checkout. Could you check whether the charge is correct?',[
('Why does a shipping fee appear?','The discounted goods total is below the free-shipping threshold','The customer ordered before July 1|Loyalty customers are excluded from free shipping|Tax has increased the goods total above $200','質問：配送料が表示されるのはなぜですか。\n正解：割引後の商品額が送料無料の基準未満だから。','210ドルの10%引きは189ドル。基準は割引前ではなく割引後なので、200ドルに届きません。','The threshold is based on the value of goods after discounts, excluding tax.'),
('What is the order total including shipping but excluding tax?','$204','$189|$200|$225','質問：配送料を含み、税金を除いた注文総額はいくらですか。\n正解：204ドル。','商品210×0.9＝189ドルに、配送料15ドルを加えて204ドルです。','orders below $200 will incur a $15 shipping fee')])

assert len(items)==120, len(items)
assert len({q['id'] for q in items})==len(items)
for q in items:
    assert len(set(q['options']))==4 and 0<=q['answer']<4
    assert q['explanation'] and q['translation']
    if q['kind']=='cloze': assert q['text'].count('_____')==1
    else: assert q['proof'] in q['passage'], q['id']
(ROOT/'questions.json').write_text(json.dumps({'schemaVersion':1,'packId':'rail-original-1','title':'Rail English オリジナル120問','questions':items},ensure_ascii=False,indent=2),encoding='utf-8')
print('Original questions:',len(items))
for lv in [730,800,850]:
 print(lv,len([q for q in items if q['level']==lv]),'items')
